# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)
User.create(first_name: "Matthew", last_name: "Giardina", age: 27)
User.create(first_name: "Jennifer", last_name: "Giardina", age: 27)
User.create(first_name: "Martin", last_name: "Giardina", age: 27)
User.create(first_name: "Joe", last_name: "Giardina", age: 27)
User.create(first_name: "Mark", last_name: "Giardina", age: 27)
User.create(first_name: "Jon", last_name: "Giardina", age: 27)
User.create(first_name: "Milton", last_name: "Giardina", age: 27)
User.create(first_name: "Jeff", last_name: "Giardina", age: 27)
User.create(first_name: "Matthew", last_name: "Giardina", age: 27)
User.create(first_name: "Matthew", last_name: "Giardina", age: 27)
User.create(first_name: "Matthew", last_name: "Giardina", age: 27)
User.create(first_name: "Matthew", last_name: "Giardina", age: 27)
User.create(first_name: "Matthew", last_name: "Giardina", age: 27)
User.create(first_name: "Matthew", last_name: "Giardina", age: 27)
User.create(first_name: "Matthew", last_name: "Giardina", age: 27)
User.create(first_name: "Matthew", last_name: "Giardina", age: 27)
User.create(first_name: "Matthew", last_name: "Giardina", age: 27)
User.create(first_name: "Matthew", last_name: "Giardina", age: 27)
User.create(first_name: "Matthew", last_name: "Giardina", age: 27)
User.create(first_name: "Matthew", last_name: "Giardina", age: 27)
User.create(first_name: "Matthew", last_name: "Giardina", age: 27)
User.create(first_name: "Matthew", last_name: "Giardina", age: 27)
User.create(first_name: "Matthew", last_name: "Giardina", age: 27)
User.create(first_name: "Matthew", last_name: "Giardina", age: 27)
User.create(first_name: "Matthew", last_name: "Giardina", age: 27)
User.create(first_name: "Matthew", last_name: "Giardina", age: 27)
User.create(first_name: "Matthew", last_name: "Giardina", age: 27)
User.create(first_name: "Matthew", last_name: "Giardina", age: 27)
User.create(first_name: "Matthew", last_name: "Giardina", age: 27)
User.create(first_name: "Matthew", last_name: "Giardina", age: 27)
User.create(first_name: "Matthew", last_name: "Giardina", age: 27)
User.create(first_name: "Matthew", last_name: "Giardina", age: 27)
User.create(first_name: "Matthew", last_name: "Giardina", age: 27)
User.create(first_name: "Matthew", last_name: "Giardina", age: 27)
User.create(first_name: "Matthew", last_name: "Giardina", age: 27)
